### Target guided ordinal encoding  or Mean Target Encoding
(used to transform high-cardinality categorical variables into numerical features based on the average target value for each category)

it is a technique used to encode the categoriacal varible based ton the relationship between the target variables 



Instead of creating dozens or hundreds of binary columns (like in One-Hot Encoding) or assigning arbitrary integers (like in Standard Ordinal Encoding), Target Encoding ranks and orders categories using the expected value of the target label $y$ given the category $x = k$.

In [2]:
import pandas as pd

df = pd.DataFrame({
    'City': ['Austin', 'Austin', 'Austin', 'Seattle', 'Seattle', 'Seattle', 'Denver', 'Austin'],
    'Bought_House': [200,150, 500, 100, 450, 320, 780, 190]
})
df

      City  Bought_House
0   Austin           200
1   Austin           150
2   Austin           500
3  Seattle           100
4  Seattle           450
5  Seattle           320
6   Denver           780
7   Austin           190

In [5]:
# to get the city use the groupby command 
df.groupby('City')['Bought_House'].mean().to_dict()

{'Austin': 260.0, 'Denver': 780.0, 'Seattle': 290.0}

In [6]:
mean_price = df.groupby('City')['Bought_House'].mean().to_dict()

In [8]:
df['Bought_House'] = df['City'].map(mean_price)
df['Bought_House']

0    260.0
1    260.0
2    260.0
3    290.0
4    290.0
5    290.0
6    780.0
7    260.0
Name: Bought_House, dtype: float64

In [9]:
df[['City' , 'Bought_House']]

      City  Bought_House
0   Austin         260.0
1   Austin         260.0
2   Austin         260.0
3  Seattle         290.0
4  Seattle         290.0
5  Seattle         290.0
6   Denver         780.0
7   Austin         260.0

In [10]:
import seaborn as sns

dataset = sns.load_dataset('tips')

In [11]:
dataset

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [13]:
dataset[['time' , 'total_bill']]

       time  total_bill
0    Dinner       16.99
1    Dinner       10.34
2    Dinner       21.01
3    Dinner       23.68
4    Dinner       24.59
..      ...         ...
239  Dinner       29.03
240  Dinner       27.18
241  Dinner       22.67
242  Dinner       17.82
243  Dinner       18.78

[244 rows x 2 columns]

In [14]:
dataset.groupby('time')['total_bill'].mean()

time
Lunch     17.168676
Dinner    20.797159
Name: total_bill, dtype: float64

In [15]:
dataset.groupby('time')['total_bill'].mean().to_dict()

{'Lunch': 17.168676470588235, 'Dinner': 20.79715909090909}

In [16]:
mean_time = dataset.groupby('time')['total_bill'].mean().to_dict()

In [18]:
dataset['total_bill'] = dataset['time'].map(mean_time)

In [20]:
dataset[['time' , 'total_bill']]

       time total_bill
0    Dinner  20.797159
1    Dinner  20.797159
2    Dinner  20.797159
3    Dinner  20.797159
4    Dinner  20.797159
..      ...        ...
239  Dinner  20.797159
240  Dinner  20.797159
241  Dinner  20.797159
242  Dinner  20.797159
243  Dinner  20.797159

[244 rows x 2 columns]